### ISSUE TITLE
DnD of root children

### ISSUE THREAD

**Issue by abesk** [pjekel/cbtree#31]
Hello, changing order with drag'n drop of root children is not working. After I drop the item, it appears on the end.
Children of non root nodes works good.

**Comment by pjekel** [comment]
Please provide the following information:

What dojo version are you using?
What cbtree version? (e.g 0.9.1 - 0.9.3)
What store are you using?
Are you using any store wrappers? (Observable/Eventable)
What model type are you using? (identify the directory e.g cbtree/model or cbtree/models)
What extensions are you using?

In addition, please:

List the smallest possible set of data demonstrating the problem.
Any other information regarding your environment that may be of interest.

**Comment by abesk** [comment]
I'm using Dojo 1.9.0, cbtree 0.9.3, ItemFileWriteStore with no wrapper and model cbtree/models/ForestStoreModel

Here is some example code:
var layers= {
    identifier: "id",
    label: "label",
    items: [
        {id: "id1", label: "Label1", type: "layer",  checked: true},
        {id: "id2", label: "Label2", type: "folder", checked: false, children : [/_children_/]}
        /_etc_/ 
    ]
};  
var store = new ItemFileWriteStore( {
    data: layers
});

var model = new ForestStoreModel( {
    store: store,
    rootId: "rootItem"
});

**Comment by pjekel** [comment]
Whenever an item was attached to the root the location of the item was not taken into consideration, the issue has been fixed. However, there still remains a bug in dijit/tree/dndSource.js:

When an item is moved within the same tree, dndSource expands the item immediately following the item dropped. In order to fix this problem you would have to insert the following line to dijit/tree/dndSource.js:

Line 451: target = childTreeNode.getParent();

After the addition, the code should look like:

``` javascript
if(source == this){
  // This is a node from my own tree, and we are moving it, not copying.
  // Remove item from old parent's children attribute.
  // TODO: dijit/tree/dndSelector should implement deleteSelectedNodes()
  // and this code should go there.

  if(typeof insertIndex == "number"){
    if(newParentItem == oldParentItem && childTreeNode.getIndexInParent() < insertIndex){
      insertIndex -= 1;
    }
  }
  model.pasteItem(childItem, oldParentItem, newParentItem, copy, insertIndex, before);
  target = childTreeNode.getParent();
} else {
   ...
}
```

Please checkout cbtree/models/ForestStoreModel.js and cbtree/models/ItemWriteStoreEX.js
Hope this helps

**Comment by abesk** [comment]
Thank you, now it works!
