### ISSUE TITLE
 dojo 1.9.1 : InvalidVersionError: cbtree/Tree::_assertVersion(): invalid dojo or dijit version

### ISSUE THREAD

**Issue by bartl-siggis** [pjekel/cbtree#38]
Hi , 
I'm upgrading from dojo 1.7 to dojo 1.9.1(which is the new version with the Arcgis api 3.7)
and i'm getting the following error when using the Cbtree : 
"InvalidVersionError: cbtree/Tree::_assertVersion(): invalid dojo or dijit version"

I don't know if the Cbtree supports version 1.9.1 yet in which case the error is justified and you can ignore the rest of this issue.

but if not : 
apparently the dojo.version.minor == 10 for 1.9.1 
and
dojoVers = (dojo.version.major \* 10) + dojo.version.minor;
makes dojoVers = 20 , 
which makes that the error is thrown.

I have bypassed this in the debugger and the cbtree seems to be working fine so far.

**Comment by pjekel** [comment]
cbtree 0.9.3-x works with dojo 1.8.x and 1.9.x, it looks to me that you downloaded dojo directly from [github](https://github.com/dojo/dojo/tree/master/_base) instead of the [dojo download page](http://dojotoolkit.org/download/)

Please check line 95 of dojo/_base/kernel.js on your system, if the minor version is 10 you definitely have the wrong dojo version.

The dojo github repository is the development environment of dojo itself...

**Comment by bartl-siggis** [comment]
ok that explains it,

I have indeed downloaded dojo from the github repo directly.

I'l change my dojo version asap so this problem shouldnt resurface.

thx for the info.
