### ISSUE TITLE
Unable to load the same tree twice

### ISSUE THREAD

**Issue by ClementYap** [pjekel/cbtree#50]
Hi Thank you for your help.
It has worked with your solution. There are two buttons which triggered to call function refreshStore. All it takes a store is to be closed and be loaded with a new set of data.

After setting clearOnClose propertyof the store  to true,
then:-

function refreshStore(givenDB, givenCard, givenBatch)
{request.post('list_tree.php', {data:{nameDB : givenDB, nameCard : givenCard,
selectedBatch : givenBatch},
handleAs: "json" 
}).then
    (function(response)
        {try
            {if(response.msg)
                 {
                       registry.byId("corner3").model.store.close();
                       registry.byId("corner3").model.store.load({data:(response.msg), 
                           getChildren: function(object)
                           {
                                  return tree3.query({parent: object.id});
                           }
                 }
            }
        catch(e)
        {
            console.debug("Error: When refreshing tree, "+e);
        }
    })
}

First try it worked, then second try it does not work.
The error caught : TypeError: this.onLoadDeferred is undefined.

I am using version dojo 1.8 and cdtree 0.9.4.
I think it has to do with the old version in which has to do with dojo/connect, instead of dojo/on, isn't it?
Please advise. Thanks
regards 
Clement

**Comment by pjekel** [comment]
Clement,

Thanks for the report, it turns out the internal dijit/Tree variable `pendingCommandsDeferred` in dojo 1.8 changed to `pendingCommandsPromise` in dojo 1.9. I have fixed the cbtree/Tree to be compatible with both dojo 1.8 and 1.9. An updated version of `cbtree/Tree.js` is available at:
https://github.com/pjekel/cbtree/blob/master/Tree.js

Please download the `cbtree/Tree.js` directly from the github master repository and let me know if that fixed the problem.

**Comment by ClementYap** [comment]
Hi Finally, you have saved my day and my job!
Yes indeed I have tried two buttons several times and the tree is loaded several times too.
THANK YOU VERY MUCH!

regards 
Clement
