### ISSUE TITLE
this.declaredClass doesn't have sense for anonymous AMD modules

### ISSUE THREAD

**Issue by vvoovv** [pjekel/cbtree#7]
An alternative might be require.toAbsMid("./Tree") where require is context sensitive require.
However it's not much different from simply writing cbtree/Tree

**Comment by pjekel** [comment]
I was thinking of declaring something like '_moduleName' and use that instead of this.declaredClass 

-----Original Message-----
From: Vladimir Elistratov [mailto:reply@reply.github.com] 
Sent: Monday, April 09, 2012 5:07 AM
To: pjekel
Subject: [cbtree] this.declaredClass doesn't have sense for anonymous AMD modules (#7)

An alternative might be require.toAbsMid("./Tree") where require is context sensitive require.
However it's not much different from simply writing cbtree/Tree

---

Reply to this email directly or view it on GitHub:
https://github.com/pjekel/cbtree/issues/7
